# -------------------------------------------------------------
# Default engine behaviour
# -------------------------------------------------------------
engine:
  # llm | local | hybrid | dual
  # llm is now the default
  mode: llm

  # Grey zone for *hybrid* mode
  # (Gateway is called when lower ≤ sim ≤ upper)
  hybrid_thresholds:
    lower: 0.30
    upper: 0.85

# -------------------------------------------------------------
# Argo-gateway LLM settings
# -------------------------------------------------------------
llm:
  model: gpto3mini        # auto-routes to apps-dev
  stream: false
  user: ${ARGO_USER}      # export ARGO_USER=<your-login>

# -------------------------------------------------------------
# Local embedding model
# -------------------------------------------------------------
local:
  model_id: NeuML/pubmedbert-base-embeddings