# ╭─────────────────────────────────────────────────────────────╮
# │  Concordia – baseline configuration (July 2025)            │
# ╰─────────────────────────────────────────────────────────────╯

engine:
  # Allowed: llm | local
  #
  # • llm   – every pair goes to the Gateway LLM (cosine still logged)
  # • local – cosine-only heuristic, no Gateway calls
  #
  mode: llm

# ──────────────────────────────────────────────────────────────
llm:                      # Argo Gateway settings
  model: gpto3mini        # o-series ⇒ auto-env = apps-dev
  stream: false           # set true to use /streamchat/ endpoint
  user: ${ARGO_USER}      # export ARGO_USER=<anl-login>

# ──────────────────────────────────────────────────────────────
local:                    # Local embedding model
  model_id: NeuML/pubmedbert-base-embeddings
  # If you want SPECTER2 instead, flip the id and run once so it downloads:
  # model_id: allenai/specter2